### ISSUE TITLE
Diagrama de casos de uso del Sistema

### ISSUE THREAD

**Issue by lorenaagm** [lorenaagm/TAREA-2#2]
Identificar los actores, casos de uso y sus relaciones. (Solo el diagrama, en esta fase no vamos a elaborar la especificación).

**Comment by NuriaVP** [comment]
Se puede ver en el PDF adjunto del trabajo, en el apartado b de esta fase de inicio.

**Comment by juz1001** [comment]
https://github.com/lorenaagm/TAREA-2/blob/main/Captura.PNG

**Comment by juz1001** [comment]
![Captura](https://user-images.githubusercontent.com/80346647/119168549-4ceb1180-ba61-11eb-9514-da70a755063e.PNG)
