### ISSUE TITLE
Especificación de los actores del Sistema

### ISSUE THREAD

**Issue by lorenaagm** [lorenaagm/TAREA-2#3]
Especificación de los actores del Sistema que se hayan identificado en el diagrama de casos de uso, es decir, los diferentes tipos de usuarios y otros sistemas con los que deba interactuar el sistema a desarrollar. Se rellenará una plantilla con los siguientes datos: el número de actor, un nombre descriptivo y la descripción, donde se explicarán las funcionalidades que podrá ejecutar el actor en el sistema.

**Comment by NuriaVP** [comment]
Se puede ver en el apartado c de la fase de inicio del PDF.
