### ISSUE TITLE
Elaborar un diagrama de secuencia o colaboración

### ISSUE THREAD

**Issue by juz1001** [lorenaagm/TAREA-2#5]
Para cada caso de uso, elaborar un diagrama de secuencia o colaboración. Al menos debe realizarse un diagrama de cada tipo.

**Comment by juz1001** [comment]
Se puede ver en el PDF.

**Comment by juz1001** [comment]
![Captura 2](https://user-images.githubusercontent.com/80346647/119168831-a05d5f80-ba61-11eb-9b5a-6417a9b82f02.PNG)

**Comment by juz1001** [comment]
![Captura](https://user-images.githubusercontent.com/80346647/119168927-b8cd7a00-ba61-11eb-8ed7-9f92f19c3706.PNG)

**Comment by noeliapg** [comment]
![diagrama de secuencia de gestionar recepción](https://user-images.githubusercontent.com/80347064/119168978-c97df000-ba61-11eb-830a-a157c61361ba.PNG)

**Comment by noeliapg** [comment]
![Uploading diagrama de secuencia dar de alta a los usuarios.PNG…]()

**Comment by noeliapg** [comment]
![diagrama de secuencia dar de alta a los usuarios](https://user-images.githubusercontent.com/80347064/119169252-13ff6c80-ba62-11eb-84e5-a00d4136add2.PNG)

**Comment by juz1001** [comment]
![Uploading Captura5.PNG…]()

**Comment by noeliapg** [comment]
![diagrama de secuencia obtener informe de incidencias](https://user-images.githubusercontent.com/80347064/119169354-2f6a7780-ba62-11eb-8a14-cf2cd3907a4a.PNG)

**Comment by juz1001** [comment]
![Captura5](https://user-images.githubusercontent.com/80346647/119169362-309ba480-ba62-11eb-8f59-6057f39bfaa0.PNG)

**Comment by juz1001** [comment]
![ok](https://user-images.githubusercontent.com/80346647/119169505-604aac80-ba62-11eb-832d-60bc97feac71.PNG)

**Comment by NuriaVP** [comment]
![nuria colaboracion](https://user-images.githubusercontent.com/80346545/119172164-e1577300-ba65-11eb-8c1d-a6ff33653853.PNG)
