### ISSUE TITLE
Diagrama de clases general del Sistema completo

### ISSUE THREAD

**Issue by juz1001** [lorenaagm/TAREA-2#6]
Diagrama de clases general del Sistema completo. No es necesario incluir los atributos y métodos de cada clase, únicamente identificar las relaciones, su nombre y multiplicidad.

**Comment by lorenaagm** [comment]
Se puede ver en el apartado c) del ejercicio 2 del pdf adjunto

**Comment by lorenaagm** [comment]
https://github.com/lorenaagm/TAREA-2/blob/89f5a90c7d6138ca78f92308af729243aa407bfd/clase.png

**Comment by lorenaagm** [comment]
![Uploading clase.png…]()

**Comment by lorenaagm** [comment]
![clase](https://user-images.githubusercontent.com/80346403/119168693-77d56580-ba61-11eb-9221-8ef6f5b76a4d.png)
