### ISSUE TITLE
Realizar prototipo de pantallas

### ISSUE THREAD

**Issue by albamiguel** [lorenaagm/TAREA-2#7]
Para simular la construcción del sistema, hemos realizado un prototipo de pantallas, el cual representa las funcionalidades principales de la aplicación que hemos construido.
Se puede visualizar el prototipo de pantallas en el pdf.

**Comment by albamiguel** [comment]
![Captura1](https://user-images.githubusercontent.com/80346538/119168830-a05d5f80-ba61-11eb-9a1d-8a2133b94f01.PNG)

**Comment by albamiguel** [comment]
![Captura2](https://user-images.githubusercontent.com/80346538/119169224-0ba73180-ba62-11eb-8207-f67be9e90eea.PNG)

**Comment by lorenaagm** [comment]
![lore1](https://user-images.githubusercontent.com/80346403/119169553-7193b900-ba62-11eb-8ab6-7b5496c0dd47.PNG)

**Comment by lorenaagm** [comment]
![lore2](https://user-images.githubusercontent.com/80346403/119169593-7c4e4e00-ba62-11eb-806e-53b13c2b2ca9.PNG)

**Comment by lorenaagm** [comment]
![h](https://user-images.githubusercontent.com/80346403/119170304-5bd2c380-ba63-11eb-92e7-b9d4d73b2752.PNG)

**Comment by albamiguel** [comment]
![h2](https://user-images.githubusercontent.com/80346538/119170406-7e64dc80-ba63-11eb-828c-ed2883f1afce.PNG)

**Comment by NuriaVP** [comment]
![j](https://user-images.githubusercontent.com/80346545/119172232-f92ef700-ba65-11eb-80db-06510ee84b29.PNG)

**Comment by NuriaVP** [comment]
![j 2](https://user-images.githubusercontent.com/80346545/119172250-00560500-ba66-11eb-88f6-4f6a1381724d.PNG)

**Comment by NuriaVP** [comment]
![j 3](https://user-images.githubusercontent.com/80346545/119172269-077d1300-ba66-11eb-8ef7-6ff46823ad9c.PNG)
